# Vezbe 13
# Ovaj fajl se koristi iskljucivo za Docker Compose.
# Prometheus u Kubernetes klasteru se konfigurise putem ServiceMonitora
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["user-service:8080"]
