# Ovaj manifest sluzi za kreiranje MariaDB klastera koristeci MariaDB Operator.
# MariaDB je fork MySQL-a koji radi na vrlo slican nacin kao MySQL.
# MariaDB moze da radi sa istim bibliotekama kao MySQL, pa ne morate da menjate
# same projekte. Dovoljno je samo da promenite connection string.
# MariaDB ne koristi MySQL Ruter. Operator ce automatski napraviti Service za
# vas MariaDB klaster (videti servise sa "kubectl get services").
# Dovoljno je da koristite taj servis direktno za pristup bazi podataka.
# Ovo je detaljno objasnjeno na vezbama 13 na prvom casu.
apiVersion: v1
kind: Secret
metadata:
  # Promeniti naziv tako da bude formata:
  # "mariadb-<naziv-vaseg-tima>-creds",
  # npr "mariadb-banka-1-creds".
  name: mariadb-vezbe-creds
  namespace: __NAMESPACE__
data:
  # Password je "raf-si".
  password: cmFmLXNp
---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  # Promeniti naziv tako da bude formata:
  # "mariadb-<naziv-vaseg-tima>",
  name: mariadb-vezbe
  namespace: __NAMESPACE__
spec:
  # Naziv default baze podataka.
  # Promeniti naziv baze podataka tako da odgovara vasim mikroservisima.
  # Ukoliko vam trebaju DODATNE baze podataka pored ove default,
  # napraviti bazu podataka koristeci Database resurs, npr:
  # https://github.com/mariadb-operator/mariadb-operator/blob/main/examples/manifests/mariadb_v1alpha1_database.yaml
  database: vezbe
  # Korisnicko ime za korisnika koji ce imati pristup bazi.
  # Ovo je novi nalog pored "root" naloga, ali mozete koristiti i "root".
  username: admin
  
  # Referenca na Secret sa password-om.
  # Promeniti name ukoliko ste menjali naziv Secret-a.
  passwordSecretKeyRef:
    name: mariadb-vezbe-creds
    key: password
  # Referenca na Secret sa password-om.
  # Promeniti name ukoliko ste menjali naziv Secret-a.
  rootPasswordSecretKeyRef:
    name: mariadb-vezbe-creds
    key: password

  # Promeniti storageClassName ukoliko deployujete bazu
  # na cloud hosted Kubernetes. Dostupne StorageClass-ove mozete videti sa:
  # "kubectl get storageclass".
  volumeClaimTemplate:
    resources:
      requests:
        storage: 2Gi
    storageClassName: nfs-client
    accessModes:
      - ReadWriteOnce

  ###############################
  # NE MENJATI PARAMETRE ISPOD! #
  ###############################
  connection:
    secretName: mariadb-conn
    secretTemplate:
      key: dsn

  image:
    repository: mariadb
    tag: "10.11.3"
    pullPolicy: IfNotPresent

  port: 3306

  replicas: 3

  replication:
    primary:
      podIndex: 0
      automaticFailover: true
      service:
        type: ClusterIP
      connection:
        secretName: primary-mariadb-conn
        secretTemplate:
          key: dsn
    replica:
      waitPoint: AfterCommit
      gtid: CurrentPos
      connectionTimeout: 10s
      connectionRetries: 10
      syncTimeout: 10s
    syncBinlog: true

  myCnf: |
    [mysqld]
    bind-address=0.0.0.0
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  service:
    type: ClusterIP
